import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import ProviderComponent from "~/utils/Provider";
import Navbar from "~/components/Navbar";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="flex flex-col min-h-screen">
        <ProviderComponent>
          <Navbar />
          <div className="flex-grow">
            {children}
          </div>
        </ProviderComponent>
      </body>
    </html>
  );
}
